---
apiVersion: template.openshift.io/v1
kind: Template
message: |-
  The following Job has been created: ${NAME}
metadata:
  name: installplan-approver-job-template
objects:
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: ${NAME}
    namespace: ${TARGET_NAMESPACE}
  spec:
    template:
      spec:
        containers:
          - image: registry.redhat.io/openshift4/ose-cli:v4.4
            command:
              - /bin/bash
              - -c
              - |
                export HOME=/tmp/approver
                oc project ${NAMESPACE}
                while true; do
                    if [ $(oc get installplan | grep -v NAME | wc -l) -gt 1 ]; then
                       break
                    fi
                    export installplan=$(oc get installplan -o=jsonpath='{.items[0].metadata.name}')
                    if [ $(oc get installplan $installplan -o jsonpath="{.spec.approved}") = "false" ]; then
                       oc patch installplan $installplan --type=json -p='[{"op":"replace","path": "/spec/approved", "value": true}]'
                       break
                    fi
                    if [ $(oc get installplan $installplan -o jsonpath="{.spec.approved}") = "true" ]; then 
                       break
                    fi
                    sleep ${SLEEP}
                done
            imagePullPolicy: Always
            name: installplan-approver
            env:
            - name: SLEEP
              value: "20"
            - name: NAMESPACE
              value: ${TARGET_NAMESPACE}
        dnsPolicy: ClusterFirst
        restartPolicy: OnFailure
        serviceAccount: ${SERVICE_ACCOUNT}
        serviceAccountName: ${SERVICE_ACCOUNT}
        terminationGracePeriodSeconds: 30
parameters:
- name: NAME
  required: true
  description: Name of the Job to create
- name: TARGET_NAMESPACE
  required: true
  description: A namespace for the Job to target
- name: SERVICE_ACCOUNT
  required: true
  description: A ServiceAccount job will use
